In [1]:
test = [1,2,3]
for i in test:
    print(i)

1
2
3


In [1]:
test = [[1,2,3], [2,3,1], [2,2,2], [3,3,3]]
for t in test:
    print(t)

[1, 2, 3]
[2, 3, 1]
[2, 2, 2]
[3, 3, 3]


In [3]:
import torch

# 두 텐서를 만들어 리스트에 담아서 전달
result = torch.stack([torch.tensor([False, False]), torch.tensor([False, False])], dim=-1)
print(result)


tensor([[False, False],
        [False, False]])


In [8]:
import torch
from torch import tensor
batch_dim = 2
pos_rew = torch.zeros(batch_dim)
final_rew = pos_rew.clone()
        
final_reward = 1
on_goal = tensor([False, True])
final_rew[on_goal] = final_reward
print(final_rew)
print(final_rew[on_goal])

final_rew[on_goal] += 1
print(final_rew)

tensor([0., 1.])
tensor([1.])
tensor([0., 2.])


In [12]:
target_idx = torch.zeros(batch_dim)
print(target_idx)
print(int(target_idx[0].item()))

tensor([0., 0.])
0
